<?xml version="1.0" encoding="utf-8"?><Database Name="academy_net" Class="CustomersRevervationsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-VBF6SCE\SQLEXPRESS;Initial Catalog=academy_net;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="academy_netConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Customers" Member="Customers">
    <Type Name="Customer">
      <Column Name="CostumerID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BirthDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Location" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ZIPCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Customer_Reservation" Member="Reservations" ThisKey="CostumerID" OtherKey="CostumerID" Type="Reservation" />
    </Type>
  </Table>
  <Table Name="dbo.Reservations" Member="Reservations">
    <Type Name="Reservation">
      <Column Name="CarID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CarPlate" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="CostumerID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ReservStatsID" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="StartDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="EndDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Location" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CouponCode" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Association Name="Customer_Reservation" Member="Customer" ThisKey="CostumerID" OtherKey="CostumerID" Type="Customer" IsForeignKey="true" />
    </Type>
  </Table>
</Database>